/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.beegash.pharmacymedicinesystem;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fener
 */
public class CompanyListBackUp extends javax.swing.JFrame {

    /**
     * Creates new form CompanyList
     */
    String[] columnNames = {"Company Name", "Shipping Adress", "Phone Number"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    static ArrayList<Company> companyList = new ArrayList<>();
    static boolean isCompanyListInitialized = false;
    Company cst1 = new Company("Büyükada Eczanesi", "Maden Mahallesi, Çınar Caddesi, No:4/A Büyükada / Adalar / Istanbul", "0(216) 382-67-56");
    Company cst2 = new Company("Hayat Eczanesi", "Heybeliada Mahallesi, Ayyıldız Caddesi No:43 Heybeliada / Adalar / Istanbul", "0(216) 612-91-91");
    Company cst3 = new Company("Ecem Eczanesi", "Arnavutköy Merkez Mahallesi, Eski Edirne Asfaltı Caddesi No:1340/A Arnavutköy / Istanbul", "0(212) 681-01-80");
    Company cst4 = new Company("Taşçı Eczanesi", "Fatih Mahallesi, Velioğlu Caddesi, No:62/A Bağcılar / Istanbul", "0(212) 651-63-24");
    Company cst5 = new Company("Kent Eczanesi", "Siyavuşpaşa Mahallesi, Barbaros Caddesi, No:40/A Siyavuşpaşa Bahçelievler / Istanbul", "0(212) 442-46-42");
    Company cst6 = new Company("Marmara Eczanesi", "Çamlık Mahallesi, Deniz Sokak No:16/B Çekmeköy / Istanbul", "0(216) 642-53-52");
    Company cst7 = new Company("Merkez Şifa Eczanesi", "Mimar Sinan Mahallesi, 79. Sokak No:23/D Esenler / Istanbul", "0(212) 611-40-50");
    Company cst8 = new Company("Ferit Gündoğan Eczanesi", "Kavaklı Mahallesi, Kavaklı Caddesi No:139/B Silivri / Istanbul", "0(212) 744-83-22");
    Company cst9 = new Company("Atlas Eczanesi", "Molla Gürani Mahallesi, Kilimci Sokak No:15/C Fındıkzade / Fatih / Istanbul", "0(212) 523-46-90");
    Company cst10 = new Company("Kuzey Eczanesi", "Mehmet Akif Mahallesi, Okay Caddesi No:19/A Ümraniye / Istanbul", "0 (216) 508-24-53");

    public CompanyListBackUp() {
        initComponents();
        setLocationRelativeTo(null);
        tableCustomer.setModel(model);
        if (!isCompanyListInitialized) {
            initCompanyList();
            isCompanyListInitialized = true;
        }

        for (Company cstm : companyList) {
            Object[] row = {cstm.getName(), cstm.getAddress(), cstm.getPhoneNumber()};
            model.addRow(row);
        }

    }

    private void initCompanyList() {
        companyList.add(cst1);
        companyList.add(cst2);
        companyList.add(cst3);
        companyList.add(cst4);
        companyList.add(cst5);
        companyList.add(cst6);
        companyList.add(cst7);
        companyList.add(cst8);
        companyList.add(cst9);
        companyList.add(cst10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        btnCloseWindow = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Company Name:");

        jLabel2.setText("Shipping Adress:");

        jLabel3.setText("Phone :");

        btnAddCustomer.setText("Add New Company");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCompanyName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddCustomer)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddCustomer)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCustomer);

        btnCloseWindow.setText("Close Window");
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setText("Remove Company");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteCustomer)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseWindow)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCloseWindow)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteCustomer)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void refreshTable() {
        model.setRowCount(0);
        for (Company cstm : companyList) {
            Object[] row = {cstm.getName(), cstm.getAddress(), cstm.getPhoneNumber()};
            model.addRow(row);
        }
    }
    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWindowActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_btnCloseWindowActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        String name = txtCompanyName.getText();
        String address = txtAdress.getText();
        String phone = txtPhone.getText();
        if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a company name.");
            refreshTable();
            return;
        }

        for (Company cmpny : companyList) {
            if (cmpny.getName().equalsIgnoreCase(name)) {
                JOptionPane.showMessageDialog(this, "A company with the same name already exists.");
                refreshTable();
                return;
            }
        }

        if (address.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an address.");
            refreshTable();
            return;
        }
        if (phone.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a phone number.");
            refreshTable();
            return;
        }

        Company company = new Company(name, address, phone);

        companyList.add(company);
        for (Company cmpny : companyList) {
            Object[] row = {cmpny.getName(), cmpny.getAddress(), cmpny.getPhoneNumber()};
            model.addRow(row);
        }
        refreshTable();
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:

        int selectedRow = tableCustomer.getSelectedRow();
        if (selectedRow != -1) {
            companyList.remove(selectedRow);
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Company sucsessfully removed");
        }
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyListBackUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyListBackUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyListBackUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyListBackUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyListBackUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
