/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.beegash.pharmacymedicinesystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fener
 */
public class CompanyList extends javax.swing.JFrame {

    /**
     * Creates new form CompanyList
     */
    Connection conn;
    String[] columnNames = {"Company Id", "Company Name", "Shipping Adress", "Phone Number"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    private DefaultTableModel tableModel;
    static ArrayList<Company> companyList = new ArrayList<>();
    static boolean isCompanyListInitialized = false;
    Company cst1 = new Company(1, "Büyükada Eczanesi", "Maden Mahallesi, Çınar Caddesi, No:4/A Büyükada / Adalar / Istanbul", "0(216) 382-67-56");
    Company cst2 = new Company(2, "Hayat Eczanesi", "Heybeliada Mahallesi, Ayyıldız Caddesi No:43 Heybeliada / Adalar / Istanbul", "0(216) 612-91-91");
    Company cst3 = new Company(3, "Ecem Eczanesi", "Arnavutköy Merkez Mahallesi, Eski Edirne Asfaltı Caddesi No:1340/A Arnavutköy / Istanbul", "0(212) 681-01-80");
    Company cst4 = new Company(4, "Taşçı Eczanesi", "Fatih Mahallesi, Velioğlu Caddesi, No:62/A Bağcılar / Istanbul", "0(212) 651-63-24");
    Company cst5 = new Company(5, "Kent Eczanesi", "Siyavuşpaşa Mahallesi, Barbaros Caddesi, No:40/A Siyavuşpaşa Bahçelievler / Istanbul", "0(212) 442-46-42");
    Company cst6 = new Company(6, "Marmara Eczanesi", "Çamlık Mahallesi, Deniz Sokak No:16/B Çekmeköy / Istanbul", "0(216) 642-53-52");
    Company cst7 = new Company(7, "Merkez Şifa Eczanesi", "Mimar Sinan Mahallesi, 79. Sokak No:23/D Esenler / Istanbul", "0(212) 611-40-50");
    Company cst8 = new Company(8, "Ferit Gündoğan Eczanesi", "Kavaklı Mahallesi, Kavaklı Caddesi No:139/B Silivri / Istanbul", "0(212) 744-83-22");
    Company cst9 = new Company(9, "Atlas Eczanesi", "Molla Gürani Mahallesi, Kilimci Sokak No:15/C Fındıkzade / Fatih / Istanbul", "0(212) 523-46-90");
    Company cst10 = new Company(10, "Kuzey Eczanesi", "Mehmet Akif Mahallesi, Okay Caddesi No:19/A Ümraniye / Istanbul", "0 (216) 508-24-53");

    public CompanyList() {
        tableModel = new DefaultTableModel();
        tableCustomer = new JTable(tableModel);
        initComponents();
        populateCompanyTable();
        String url = "jdbc:mysql://localhost:3306/pharmacy?zeroDateTimeBehavior=CONVERT_TO_NULL";
        String username = "root";
        String password = "1287";
        try {
            conn = DriverManager.getConnection(url, username, password);
        } catch (Exception ex) {
            System.out.println("Error" + ex.getMessage());
        }
        setLocationRelativeTo(null);

        if (!isCompanyListInitialized) {
            initCompanyList();
            isCompanyListInitialized = true;
        }

        tableCustomer.setModel(model);

        refreshTable();

    }

    private void initCompanyList() {
        companyList.add(cst1);
        companyList.add(cst2);
        companyList.add(cst3);
        companyList.add(cst4);
        companyList.add(cst5);
        companyList.add(cst6);
        companyList.add(cst7);
        companyList.add(cst8);
        companyList.add(cst9);
        companyList.add(cst10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnAddCustomer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCompanyID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        btnCloseWindow = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Company Name:");

        jLabel2.setText("Shipping Adress:");

        jLabel3.setText("Phone :");

        btnAddCustomer.setText("Add New Company");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        jLabel4.setText("Company ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(518, 518, 518)
                .addComponent(btnAddCustomer)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnAddCustomer)
                .addContainerGap())
        );

        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Company ID ", "Company Name", "Shipping Address", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCustomer.setToolTipText("");
        jScrollPane1.setViewportView(tableCustomer);

        btnCloseWindow.setText("Close Window");
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setText("Remove Company");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteCustomer)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseWindow)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCloseWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteCustomer)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void populateCompanyTable() {
        try {
            Connection connection = DBhelper.getConnection();
            PreparedStatement statement = connection.prepareStatement("SELECT * FROM companytable");
            Statement statement1 = connection.createStatement();
            ResultSet resultSet = statement1.executeQuery("SELECT * FROM companytable");

            while (resultSet.next()) {
                int companyId = resultSet.getInt("company_id");
                String companyName = resultSet.getString("company_name");
                String companyAddress = resultSet.getString("company_adress");
                String companyNumber = resultSet.getString("company_num");

                tableModel.addRow(new Object[]{companyId, companyName, companyAddress, companyNumber});
            }

            resultSet.close();
            statement1.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void refreshTable() {
        model.setRowCount(0);

        String sql = "SELECT * FROM companytable";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});

            }

        } catch (Exception ex) {
            System.out.println("Error" + ex.getMessage());
        }
    }
    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWindowActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_btnCloseWindowActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        int id;
        String name = txtCompanyName.getText();
        String address = txtAdress.getText();
        String phone = txtPhone.getText();
        if (name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a company name.");
            refreshTable();
            return;
        }

        for (Company cmpny : companyList) {
            if (cmpny.getCompanyName().equalsIgnoreCase(name)) {
                JOptionPane.showMessageDialog(this, "A company with the same name or id already exists.");
                refreshTable();
                return;
            }
        }
        try {
            id = Integer.parseInt(txtCompanyID.getText());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for id.");
            refreshTable();
            return;
        }

        if (address.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an address.");
            refreshTable();
            return;
        }
        if (phone.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a phone number.");
            refreshTable();
            return;
        }

        Company company = new Company(id, name, address, phone);

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "1287");
            String query = "INSERT INTO companytable (company_id, company_name, company_adress, company_num) VALUES (?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setInt(1, company.getCompanyId());
            stmt.setString(2, company.getCompanyName());
            stmt.setString(3, company.getCompanyAddress());
            stmt.setString(4, company.getCompanyPhoneNumber());

            stmt.executeUpdate();
            stmt.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred while adding the medicine to the database.");
            refreshTable();
            return;
        }
        companyList.add(company);
        String sql = "SELECT * FROM companyTable";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tableCustomer.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});

            }

        } catch (Exception ex) {
            System.out.println("Error" + ex.getMessage());
        }

        refreshTable();
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        // TODO add your handling code here:

        int selectedRow = tableCustomer.getSelectedRow();
        if (selectedRow != -1) {
             String companyName = (String) model.getValueAt(selectedRow, 1);
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "1287");
                String query = "DELETE FROM companytable WHERE company_name = ?";
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, companyName);
                stmt.executeUpdate();
                stmt.close();
                conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "An error occurred while deleting the company from the database.");
                return;
            }

            companyList.remove(selectedRow);
            model.removeRow(selectedRow);

            JOptionPane.showMessageDialog(this, "Company sucsessfully removed");
        }
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtCompanyID;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
